### PR TITLE
Refactor the operator into golang

### PR DESCRIPTION
**Pull request by carsonoid**
This is a major overhaul but should ultimately make the operator more robust.

I would say that the operator is currently in an alpha state. It can bring multiple VitessClusters up and down at the same time and will respond to some changes to the custom resources. I am submitting the PR now as an effort to get some extra eyes on it and start iterating against it.

@derekperkins and @clintberry have been key influences in the design and motivation behind this upgrade.

### CODE REVIEW

**Comment by derekperkins** [comment]
I'm super excited about this. @enisoc and I have been talking about making an operator for almost two years, and it's awesome to finally see it come to fruition.

cc @dkhenry @sougou @jvaidya

**Comment by carsonoid** [comment]
Added sign-off and force-pushed.

**Comment by enisoc** [comment]
Since I've been unable to devote time to keep up with the community's work on the new operator, I want to be clear that I have no intention of trying to block anyone who's actually doing work. With that said, I do want to put into writing some context on why my initial prototype of the operator is the way it is (e.g. why it's in Jsonnet instead of Go).

In contrast with many apps for which Kubernetes operators have been written, Vitess was already designed to be resilient in a world of ephemeral containers (in Borg) and to be orchestrated by a declarative control plane (BCL + Vitess topology). In fact, the "topology service" in Vitess (often backed by etcd) can be thought of as an incarnation of the same pattern Kubernetes later adopted through convergent evolution (there's no direct relation). Like Kubernetes controllers, vttablets take action to reconcile real-world state in response to updates to Tablet records in topo ("updating the config makes it so"), and report back status by updating output fields in those records.

As a result of this, Vitess has a unique concern to consider when deciding where to add automation of the type that normally goes into Kubernetes Operators. Should we put the logic in the Kubernetes control plane, or in the Vitess control plane? My initial prototype of the Vitess Operator was based on my opinion that any new, non-trivial automation we needed to adapt Vitess from Borg to Kubernetes should go into the Vitess control plane; the automation in the Kubernetes control plane (the Vitess Operator) should be trivial in my opinion (essentially configuration abstraction, template expansion).

My rationale was that the Vitess control plane already contains a great deal of such automation (replication management, failovers, backup/restore, resharding, schema change workflows, etc.), and I wanted to keep new automation in the same place, working on the same Vitess-level concepts. I worried that it would become a nightmare to maintain non-trivial logic that spans both of these domains for things like automating resharding workflows in Kubernetes. I also considered that some Vitess users do not run it in Kubernetes, and would benefit from having such automation at the Vitess level.

Given the above opinion, it seemed to me that the Vitess Operator would never need anything more sophisticated than, essentially, template expansion to allow for configuration abstraction, by which I mean things like, "When I say VitessCluster, I want you to expand that to X, Y, Z Kubernetes API objects." A templating language like Jsonnet combined with Metacontroller seemed like a good fit for that, because it allows us to eliminate the vast majority of boilerplate and just say, "This is what a VitessCluster expands into; this is what a VitessShard expands into; etc."

If the group has already considered these issues and still came down on the side of Go, could someone summarize the rationale or point me to some record of it? In particular, I'm interested to know if you plan to include non-trivial automation logic in the Vitess Operator -- that is, anything that can't be ultimately boiled down to template expansion.

**Comment by derekperkins** [comment]
@enisoc Those are all good points. Having been in charge of the helm integration for the last year, there is a different cadence to core Vitess work and what is needed to operate in Kubernetes. The current charts are littered with relatively complex bash scripts, like this `ISM` call https://github.com/vitessio/vitess/blob/master/helm/vitess/templates/_shard.tpl#L60-L118. We need to make it idempotent in case it gets called multiple times, but the related upstream PR 
never materialized. https://github.com/vitessio/vitess/pull/4109. The goal is to continue to push as much upstream as possible. 

There are some more complex Kubernetes scheduling scenarios that don't ever make sense upstream. I've posted one dream case here about making sure that master pods stay on different nodes. https://github.com/vitessio/vitess-operator/issues/6. Maybe that could be handled by updating k8s labels `shard-master: true`, but there's a good chance that would cause cascading churn if not coordinated properly.

There's even this PR https://github.com/vitessio/vitess/pull/4194 about an upstream cluster manager, which would take over a decent amount of operator / kubernetes work, but there's no guarantee if/when it will get completed.

At the end of the day, as much as can live in core Vitess should, but there are always going to be edge cases specific to k8s or times when the operator will need to be more responsive than core Vitess. Where possible, the operator should just be making grpc calls to vtctld.

Not being familiar with jsonnet, I think some/most/all of that could still be solved without using the operator sdk. The main reasons for switching are: 
- while most contributors to Vitess are well versed in Go, I'm not sure that many are familiar with jsonnet
- the PlanetScale Operator is written in the operator sdk, and so keeping it in a similar framework should make it easier to share work between the two
- the person hired to write the operator, @carsonoid, has built many controllers/operators, but all with Go and not metacontroller

**Comment by enisoc** [comment]
Thanks @derekperkins. I think we generally agree on what we'd like the ideal end state to be (vitessio/vitess#4194 is a good example of what I meant; the operator could eventually just be a k8s adapter for that system). However, it sounds like you need something that works, now, and you have a plan to do that. That's fair, so I'll stay out of the way as promised and let @derekperkins have final approval on this PR. As for continuing to push as much upstream to vitessio/vitess as possible, I expect to have bandwidth to start helping out with that in April.

**Review by derekperkins — APPROVED** [review]
Let's go ahead and merge this as is, and we can start iterating quicker to get it to feature parity with the helm charts.

**Comment by carsonoid** [comment]
@derekperkins  and @enisoc before we merge this we should figure out the release process and make sure the docker image used in the deploy docs is actually pushed up. The operator Deployment is still using a placeholder for the image name.

Ideally the image should be hosted under the vitess umbrella but I don't have access to push there.

**Comment by derekperkins** [comment]
@carsonoid I just created a repo for it, https://hub.docker.com/r/vitess/operator, and granted you admin access to it.

**Comment by carsonoid** [comment]
@derekperkins image built and pushed. The deploy yaml has also been updated.

**Comment by dkhenry** [comment]
So I agree with @enisoc that as much as possible we should have automation in upstream Vitess and not in the operator, however I am coming to figure out there is a big delta between Borg/BCL and what is provided by Kubernetes. Specifically the immutable nature of Kubernetes containers means we have to do upgrades very differently then what I have been told can be done in Borg, and that needs a heavy hand in Kubernetes to keep things running without interruption to queries.

**Comment by JoshuaAndrew** [comment]
@carsonoid  Good job !

**Comment by derekperkins** [comment]
@enisoc Any further thoughts before you merge this?

**Comment by sougou** [comment]
I believe we have consent from @enisoc. So, this can go in.

I'd been meaning to chime in. I believe there's an easy way to draw the line about what should be done on the vitess side, and what should be done outside of it. It comes from the fact that vitess can run on bare-metal, or any other cloud environment. This means that it cannot depend on kubernetes.

So, any Orchestration work that requires us to call into Kubernetes will obviously have to be outside of vitess.

I do see some workarounds in the operator side (for example, `ISM`). These should ideally be fixed in vitess, eventually. And anything else that can be done by vitess should be done there, and not the operator.

Using the above ground-rules, it looks like we still need an operator. The question is: is it simple enough to be done with the metacontroller, or do we need actual code? My gut-feel is that the metacontroller is likely to be insufficient as it stands. We may have to add features to it.

With @enisoc being distracted in the past few months, not much work has gone into meta-controller. However, if it picks momentum again, we should look at going back to it. The Kubernetes ecosystem is still defining itself. Nothing is etched in stone. So, we'll have to adapt if new frameworks start to emerge as standards.

**Comment by derekperkins** [comment]
I don't have merge permission on this repo, otherwise I'd go ahead.

**Pull request merged**
